name: Run TruffleHog

on:
  push:
    branches:
      - main  # Ou a branch que quiseres monitorizar
  pull_request:
    branches:
      - main  # Ou a branch que quiseres monitorizar

permissions:
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write

jobs: 
  TruffleHog: 
    runs-on: ubuntu-latest 
    defaults: 
      run: 
        shell: bash 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4 
        with: 
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.88.9 
        continue-on-error: false 
        with: 
          path: ./ 
          base: "${{ github.event.repository.default_branch }}" 
          head: HEAD 
          extra_args: --results=verified,unknown﻿
          
      - name: Scan Results Status 
        if: steps.trufflehog.outcome == 'failure' 
        run: exit 1

