name: Run TruffleHog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.88.9
          
    - name: Scan Results Status 
      if: steps.trufflehog.outcome == 'failure' 
      run: exit 1

